---
abstract: 'Build constant classes'
author:
  - 'Robert Norris <rob@eatenbyagrue.org>'
build_requires:
  Test::More: 0.95
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Class-Constant
provides:
  Class::Constant:
    file: lib/Class/Constant.pm
    version: 0.06
requires:
  Scalar::Util: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.06
